### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by JosephKrusling** [JosephKrusling/Asteroid-Automata#3]
- [x] Asteroids - Basically just large circles, but rendered on front end as nice line-ey asteroids. When they blow up they drop coins.
- [x] Example Scripts - Pacifist (only collects coins), Psycopath (only kills, doesn't collect coins), Realist (tries to play like a normal person)
- [x] Put game server in the cloud
- [ ] Quadtree collision for performance
- [x] Create interpreter spawner server.
- [x] Write front end page to submit your script
